### ISSUE TITLE
Error while exegol update execution

### ISSUE THREAD

**Issue by Gipada** [ThePorgs/Exegol#219]
### Describe the bug

Error while executing update via "exegol update"

command "exegol update --skip-git full" works properly

### Steps To Reproduce

1. Run on Windows
2. Run 'exegol update'

### Exegol Wrapper Version

```Text
$exegol version -vvv
[*] Exegol is currently in version v4.3.4
[*] Exegol Discord serv.: https://discord.gg/cXThyp7D6P
[*] Exegol documentation: https://exegol.rtfd.io/
[D] Pip installation: On ✔                                                            
[D] Git source installation: Off 🪓                                                   
[D] Host OS: Windows (WSL2)
[D] Arch: amd64
[D] Windows release: 10.0.22631
[D] Python environment: Windows
[D] Docker engine: WSL2
[D] Docker desktop: On ✔                                                              
[D] Shell type: Windows
[D] Last wrapper update check: 02/06/2024

[*] Exegol is currently in version v4.3.4                                             
[*] Exegol Discord serv.: https://discord.gg/cXThyp7D6P
[*] Exegol documentation: https://exegol.rtfd.io/
```

### Host OS

Windows 11

### Execution logs in debug mode

```Text
$ exegol update -vvv
[*] Exegol is currently in version v4.3.4
[*] Exegol Discord serv.: https://discord.gg/cXThyp7D6P
[*] Exegol documentation: https://exegol.rtfd.io/
[D] Pip installation: On ✔                                                            
[D] Git source installation: Off 🪓                                                   
[D] Host OS: Windows (WSL2)
[D] Arch: amd64
[D] Windows release: 10.0.22631
[D] Python environment: Windows
[D] Docker engine: WSL2
[D] Docker desktop: On ✔                                                              
[D] Shell type: Windows
[D] Last wrapper update check: 02/06/2024

[D] Running update module
[!] Exegol has not been installed via git clone. Skipping wrapper auto-update
operation.
[*] If you have installed Exegol with pip, check for an update with the command pip3  
install exegol --upgrade


[D] Loading git at C:\Users\myUser\.exegol\exegol-resources
[D] Repo path: C:\Users\myUser\.exegol\exegol-resources\.git
[D] Git repository successfully loaded
[*] Updating Exegol resources                                                         
[-] It seems that something unexpected happened ...                                   
[-] To draw our attention to the problem and allow us to fix it, you can share your   
error with us (by copying and pasting it with this syntax:  <error> ```) by        
creating a GitHub issue at this address: https://github.com/ThePorgs/Exegol/issues    
[+] Thank you for your collaboration!
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\myUser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\exegol.exe\__main__.py", line 7, in <module>
  File "C:\Users\myUser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\exegol\manager\ExegolController.py", line 73, in main
    logger.critical(f"A critical error occurred while running this git command: {' '.join(git_error.command)} => {error}")
  File "C:\Users\myUser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\exegol\utils\ExeLog.py", line 79, in critical
    super(ExeLog, self).critical("{}[!]{} {}".format("[bold red]", "[/bold red]", msg), *args, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1586, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1684, in _log
    self.handle(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1028, in handle
    self.emit(record)
  File "C:\Users\myUser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\rich\logging.py", line 159, in emit
    message_renderable = self.render_message(record, message)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myUser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\rich\logging.py", line 185, in render_message
    message_text = Text.from_markup(message) if use_markup else Text(message)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myUser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\rich\text.py", line 286, in from_markup
    rendered_text = render(text, style, emoji=emoji, emoji_variant=emoji_variant)     
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     
  File "C:\Users\myUser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\rich\markup.py", line 167, in render
    raise MarkupError(
rich.errors.MarkupError: closing tag '[/<m>]' at position 3354 doesn't match any open tag
```

### Exception

```Text
[*] Exegol is currently in version v4.3.4
[*] Exegol Discord serv.: https://discord.gg/cXThyp7D6P
[*] Exegol documentation: https://exegol.rtfd.io/
[!] Exegol has not been installed via git clone. Skipping wrapper auto-update
operation.
[*] If you have installed Exegol with pip, check for an update with the command pip3  
install exegol --upgrade                                                              


[*] Updating Exegol resources                                                         
[-] It seems that something unexpected happened ...                                   
[-] To draw our attention to the problem and allow us to fix it, you can share your   
error with us (by copying and pasting it with this syntax: ``` <error> ```) by        
creating a GitHub issue at this address: https://github.com/ThePorgs/Exegol/issues    
[+] Thank you for your collaboration!
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\myUser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\exegol.exe\__main__.py", line 7, in <module>
  File "C:\Users\myUser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\exegol\manager\ExegolController.py", line 73, in main
    logger.critical(f"A critical error occurred while running this git command: {' '.join(git_error.command)} => {error}")
  File "C:\Users\myUser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\exegol\utils\ExeLog.py", line 79, in critical
    super(ExeLog, self).critical("{}[!]{} {}".format("[bold red]", "[/bold red]", msg), *args, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1586, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1684, in _log
    self.handle(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1028, in handle
    self.emit(record)
  File "C:\Users\myUser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\rich\logging.py", line 159, in emit
    message_renderable = self.render_message(record, message)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myUser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\rich\logging.py", line 185, in render_message
    message_text = Text.from_markup(message) if use_markup else Text(message)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myUser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\rich\text.py", line 286, in from_markup
    rendered_text = render(text, style, emoji=emoji, emoji_variant=emoji_variant)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     
  File "C:\Users\myUser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\rich\markup.py", line 167, in render
    raise MarkupError(
rich.errors.MarkupError: closing tag '[/<m>]' at position 3354 doesn't match any open tag
```
```


### Anything else?

_No response_

**Comment by Dramelac** [comment]
Hello @Gipada 

Indeed the wrapper doesn't handle correctly your git exception message.
You seem to have a git problem for the exegol-resources repo.

Try to go to `C:\Users\myUser\.exegol\exegol-resources` directory and run `git pull`. 
Can you then, share the error message here ?

**Comment by Gipada** [comment]
Hello,
Thanks for the update, I tried to run it as my user and here is the result : 
```
$ git pull
fatal: detected dubious ownership in repository at 'C:/Users/myUser/.exegol/exegol-resources'
'C:/Users/myUser/.exegol/exegol-resources/.git' is owned by:
        BUILTIN/Administrateurs (S-1-5-32-544)
but the current user is:
        PORTABLE/myUser (S-1-5-21-1789693909-659450144-256219876-1001)
To add an exception for this directory, call:

        git config --global --add safe.directory C:/Users/myUser/.exegol/exegol-resources
```

It seems I tried to install user admin and update does not work with my default user. I just tried run shell as admin and the update works well.

So the issue is on me, I would just suggest maybe to catch the exception and logging the advice about right/admin issue could be enough in this case.

**Comment by Dramelac** [comment]
Hello, indeed you might want to change your directory ownership to your current user to avoid future error

**Comment by ShutdownRepo** [comment]
Closing here, if you need any additional help @Gipada, feel free to hit us up, or to join the Discord server and open a ticket there, we'll be happy to help
